### ISSUE TITLE
TODO for V1

### ISSUE THREAD

**Issue by jessmartin** [etewiah/inman-offer-tracker-fe#2]
- [x] Change the offer states so that they are the real states in the mockup
- [x] Load the offer details (address, MLS #) from Firebase
- [x] Enable checkboxes to be clicked by agent and save those to Firebase
- [x] Enable (hide/show) back button and logout
- [x] Animate the wheel when checkboxes are clicked
- [x] Set up an "buyer" view that is locked into viewing a single offer
- [ ] Animate the wheel when someone clicks the checkboxes in a different browser (some kind of watch function?)
- [ ] Buy domain and get that domain set up on Netlify (just use klodova.com)
- [ ] Tell inman.com to set up redirect from inman.com/ot to "buyer" view
- [ ] It looks like crap on mobile - need to fix that

**STRETCH**
- [ ] Have a "victory" state on the last step
